<!-- Outer Frame -->
<section class="flex justify-center items-center">

  <!-- Inner Frame -->
  <section class="w-full max-w-screen-lg mt-6">
  
<p class="text-center bb s7">Hardev Sir's IELTS Offline Class Videos</p>

  <!-- Phase 1 -->
  <div data-video="1" class="mb-6 mt-12">
      <p class="text-center bb s6 mb-8">Demo Phase - Day 1 to 3</p>
      <p class="text-center bb s2 mb-3">Basic Concepts of IELTS Essay Writing</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_HWZRPDSi" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Basic-Concepts-of-IELTS-Essay-Writing.html?player=onlinerec&at=eyJpdiI6IjVJN0F2d1VzVEdkVTJZeDJLYlFsb1E9PSIsInZhbHVlIjoidDVlN2l2OUxNTHZ4Nzk2L0NJNzRDN3htNGc5emNoeFVhR0pSTGc1WTRiTT0iLCJtYWMiOiJmOThlMGFjNGMxYjg2Nzg3MjFkNDAwNWNlY2RiODA4Yzg1ZDM3ZTBjMzIyNWM0ZTUzMTliMmZhOWQyMTI4ZDc0IiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

  
      <p class="text-center bb s2 mt-10 mb-3">Basic Concepts of IELTS Graph Writing</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 54.69%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 54.69%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_Wphzpdzn" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Basics-of-IELTS-Graph-Writing.html?player=onlinerec&at=eyJpdiI6ImZtcGM4bWp4UTNxMmZBWTlqck9XVGc9PSIsInZhbHVlIjoiemUvUmhHRCtScDBnSlN2TkVRNnFuaDl3Y1htc3RvWUY3SEVTR2ZET3FrOD0iLCJtYWMiOiIyYWFkNmI2MGE1ZDRmNzVmOGJmZjMzNWQxZGI2NTRmZTZmMGU4Mjk3NjJiMmFiOTI3ZTI4NTdiMmQ3MWFjYTllIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mt-10 mb-3">Reading Lesson 1 - Introduction</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_HnSyzsD7" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Reading-Lesson-1-Introduction-To-Reading-Test.html?player=onlinerec&at=eyJpdiI6ImY3YkdURnpHYWYxZmk1SER6TStXZlE9PSIsInZhbHVlIjoiYjQ0alR1WWVQM2w1RmR6eVlIcmpPamZEMFlqL1pDQ0xyQkIxeXhrZWJMRT0iLCJtYWMiOiJkNTliZmU4Y2QwM2EwNGZkODM4OGM1MjUxMzFmODliMDcxZGYxN2EwNmJiNzdjMDk0ZGY5NWE1NmZiMWViNzQyIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mt-10 mb-3">Reading Lesson 2 - Basic Reading Tips</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_AVskVff9" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Reading-Lesson-2-Basic-Reading-Tips.html?player=onlinerec&at=eyJpdiI6ImhEME9IdStnVWNsMUNxQmpBcC9xSGc9PSIsInZhbHVlIjoiblNjYmh0REg1TjFwUEJRbFlaZWFTNENsQ0pyeWV5Ym1ubDhMaThFQmdNUT0iLCJtYWMiOiI3NThkYTI4ODgyMTk4OTRkZDgxNDY3NWJjYjY2ODg1OTliZmUwNmUyMGM5ZDcwYTVhZjk5YThmZWY3N2UyN2YwIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mt-10 mb-3">Reading Lesson 3 - Improving Reading Speed</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_bjfB9VTt" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Reading-Lesson-3-Improving-reading-speed.html?player=onlinerec&at=eyJpdiI6ImxIUWc3NXZmTXZQL2l6cERBSXF6a2c9PSIsInZhbHVlIjoiQnQzR0Q0amI0cVU5R0JuN2ZWWW5NcmRZOWJLc1hoRi9nL0NJWU1pTzU3Zz0iLCJtYWMiOiIyNTE2ZjVjZmU4ODMyZmExNjRiMjQ4MzQ0MmNmNTQ3ZGMwYTRkZjg3OTUyMDc1MjYwMmRkZTI5NzNkOTlhZjM1IiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      
  </div>

  <p class="text-center bb s6 mt-8 mb-8">Phase 2 - Day 5 to 11</p>

  <p class="text-center bb s2 mb-3">5 Big IELTS Speaking Test</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_Z0Sj3WjH" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/5-BIG-IELTS-Speaking-Part-1-TIPS.html?player=onlinerec&at=eyJpdiI6ImdWQm1NSno1eTNKdnpWSlBKSzJLenc9PSIsInZhbHVlIjoiaDJOTmlvSmVsVWtaR1oxWlNhT0xQekd1YmpLM3RTZnN5djhzUjVHQ25oST0iLCJtYWMiOiI0ZDBkNmVlOGYyYzRkN2FkZTFiMWQ0NzI3NzBiYzBiYjg0NzE1MDBkNmZiMDNiNTZlZjdmYzU0ZTkzYmUwODhjIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mb-3">Discussion Essay Masterclass</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_L77avaAV" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Discuss-Basics.html?player=onlinerec&at=eyJpdiI6InVxaXFDQkJ3TnJGNkVCbmR6SkhBaGc9PSIsInZhbHVlIjoiUGdob09SK2QxRklZVHZhbzVEdndvSVU3aUV2K1NSWjZHdWhXMHNzeGMxWT0iLCJtYWMiOiJkMmViMzQ3Njc3MjJlNDk5N2ZhODkyMDhmZmVkMDBiYjcyNDZlYzlkNDlhNGEyYjljYWM1NmRjMjRmMTM2OWMxIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mb-3">Reading Lesson 4.1 - T/F/NG Tips</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_rxMQlVHb" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Lesson-4-True-False-Not-Given.html?player=onlinerec&at=eyJpdiI6ImR2dGJ5UEIxMmZNYWMzU05oMWpXWEE9PSIsInZhbHVlIjoiT3hDZWRRTDArZkFzN2VzTGlRWDNQczhPZnRoN3lKVE0zMVQxUkEyUXlBUT0iLCJtYWMiOiIyZjgzZDdiZThkOGVhNDQ0MzU0MjIyMzdkMWRjMGIyZmM1ZTU2MGU1MmVkY2Y3ZDEzZDgxMjIyMTQ3MDA4OTUyIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mb-3">Reading Lesson 4.2 - TFNG LIVE Demonsttration</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_tyq5ZBGd" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Lesson-4-1-Live-demonstration-TFNG.html?player=onlinerec&at=eyJpdiI6ImxnY01UeFpVd1M3MC9pQ3YwMEN5WEE9PSIsInZhbHVlIjoiZkNiTllWSFMzdjB3ZDNIdXNPbDZKRGI4ajRFUHcyM25NejVJZ1l0TkdPND0iLCJtYWMiOiJkMDQyMmFhMmUwODljNjA4NWE2MjJjMjUwNjczNmIzOGYyNzA2MDRjODkwZGM0NmVlYmUxNmU5MjBhM2YxOTExIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mb-3">Reading Lesson 5.1 - Fill In The Blanks</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_JuMiW48v" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Lesson-5-Fill-In-The-Blanks.html?player=onlinerec&at=eyJpdiI6IkNldk5KMGtiUGhvdWQydHRPbTdJenc9PSIsInZhbHVlIjoiaTFmNURtRXhBRFNLbXVFejlwTTN4T09BSm50Wm9MdVd5YkxFR3FNMHJNdz0iLCJtYWMiOiI4ZmI2M2ExZDkxM2RjYTliMDc2MTYxZWZiMTZmODY4Njc3ZWUzYThlMDkwNjliMjQzNzc5MjY5NjA4ZTFkZmU5IiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mb-3">Reading Lesson 5.2 - FIB LIVE Demonstration</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_cm1s8tM5" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Lesson-5-1-Live-demonstration-FIB.html?player=onlinerec&at=eyJpdiI6IlJucVcvUjM0ZE5QUVVuaVIyaFpqeWc9PSIsInZhbHVlIjoicERVZFdtNitIT0hZbHlWbkFwc1Zsd3J0RVorUldNUGQ1NXRPT2pQUTRKUT0iLCJtYWMiOiI4ZTkwNzNiYjA2NTM5YzFkMGYzMmNiNmE5OWM0Y2Y3ZTBjMTExY2RiNmE0OWQzZjZjYWM4NmIwNjE1MDk4ZDRlIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      


  <p class="text-center bb s6 mt-8 mb-8">Phase 3 - Day 12 to 18</p>
  <p class="text-center bb s2 mb-3">7 Big IELTS Speaking Part 2 Tips</p>
  <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_jcDPjTzX" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/7-BIG-IELTS-Speaking-Part-2-TIPS-Cue-Cards.html?player=onlinerec&at=eyJpdiI6IkFMOHBHLzllQ29NTVczWFE5bWhzS3c9PSIsInZhbHVlIjoiOVNZa2s4UE80TTN4cGdzZ0tuZ1YyWkNvMWJUTU9HZXdzWDhRRlZtOXJoOD0iLCJtYWMiOiIyNTI5MmI0YzEyN2M5YjVjODViYzY1MTFkMzc4MTRjYWNlN2Q2NzVkZjQ5YjJmM2I3M2UxMzZjOTFiNzMwNjMzIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mb-3">Advantage Disadvantage Essay Masterclass</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_iobmt8Tr" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Advantages-Disadvantages-Essay-in-15-Minutes-or-less.html?player=onlinerec&at=eyJpdiI6Ik9yVmNqZExBaTNMenNNaHoyUkErM3c9PSIsInZhbHVlIjoiSlJtL0prNTloWU02T1BiSHFDQ28zYk0vNVl5dEtEa2VFQnN3ZCtwVENRND0iLCJtYWMiOiI0MjY1NmRjYWNkNDNmZGEzZTMwMWQ0Zjk5ZGI5MjFhM2ZiZjFhMjAyODg3Y2I0OWRjODZhNWZkY2U5ZjEyMmE2IiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mb-3">Line Graph Masterclass</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 69.66%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 69.66%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_aVk78ZGR" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Line-Graph-Class.html?player=onlinerec&at=eyJpdiI6InQ0bXpCNEdoc2JYcUwvaDVGODZhUmc9PSIsInZhbHVlIjoiWEZIZ2hyUUVJbnZPdkcvbEJqeWV3VG84SzVnelEwakU4ek9FYWd0OTlPRT0iLCJtYWMiOiJmMjE3NWM1Zjc4NmM0NzVjMjcxNzIwZDVmZTAyOTI1NzA5ZDYyMWU3ZTE4Mjc5MWFhNWYxZGQyOTg4NzM3YzZmIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mb-3">Introduction to deep reading</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_lygpTno0" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Introduction-To-Deep-Reading-YouTube.html?player=onlinerec&at=eyJpdiI6IlNpbXo1ck80UC9mRGkrWSswcDNIOXc9PSIsInZhbHVlIjoiRlhLYU9keVU0bndqeWNtbGNZaGU0YnZHNTNaOHY4R05HZTl4QVpwZVNQbz0iLCJtYWMiOiI3Y2YwMzkwMzExM2FmNDg4M2U3YmMxODRjMTViMDZkOWE3YzViZWYxMWNkZTEzMWNmNzU2Nzg4ODVjYzVlYzYxIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mb-3">Reading Lesson 6.1 -  WPC (Paragraph Matching)</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_yjcmVGRL" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Lesson-6-Paragraph-Matching.html?player=onlinerec&at=eyJpdiI6IjMvTjRhMFZiWko3ekphLzJCMVZWZEE9PSIsInZhbHVlIjoiVGNJKzNQVUh3SnVXcTNyR3NlQlRXeHN3SkM5RVlNeThaK09pY1oybDE1TT0iLCJtYWMiOiI3NzExYmI3YTVlYjBkNzdjNGNmODdmNjliYjFkODE3YTI0M2UxODFmY2I1MzU0OTdjZjEzMmRjNjUyOGYwMGI2IiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mb-3">Reading Lesson 6.2 - WPC Live Demonstration</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_yjcmVGRL" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Lesson-6-Paragraph-Matching.html?player=onlinerec&at=eyJpdiI6IkpybXV2SmJtazREdXkzcjBBQVBhVFE9PSIsInZhbHVlIjoiaVlLNlNaeWhlNlJIOW5NZHlFL0FacjZwRXhpam8xa1g2VTcxREVWVUgzdz0iLCJtYWMiOiJiNjY0MDI0MjU1ZTU5YzlhNGE3MmY4NDMxODQxOWMyMGE0ODRhNDcxMGQ4Y2RmMGIzYmM0OWRjNDIwNTEwNWU1IiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mb-3">Reading Lesson 7.1 - MCQ (Multiple Choice Questions)</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_ZQ7sW3ix" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Lesson-7-Multiple-Choice-Questions.html?player=onlinerec&at=eyJpdiI6ImhEK2xRYkIvRnhuMTlFVHFTNStpNmc9PSIsInZhbHVlIjoiWjJlUDFRNENMWDZGbi9LeHQ2WWVKWUk3Ry93TnF2T1pBNnhWZGZYSUE0dz0iLCJtYWMiOiIxYTc2OGNmZjEyYjg5YTBlNjQ1OGU1MGViMWM5ZGU1YjU0NTE5ZDlmYmQ3Mzk3ODE0M2Q4ZWZhOGI4ZWMxMDNjIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mb-3">Reading Lesson 7.2 - MCQ LIVE Demonstration</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_Lexkdzl7" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Lesson-7-1-Live-demonstration-MCQ.html?player=onlinerec&at=eyJpdiI6IlFyanZaQnJ4Y3FQekU5L3VaMElicEE9PSIsInZhbHVlIjoiWFFKV3puS0UxNk5lRlhKb1NOMnhicjVaeTZ0elhVTGVsNCtxUEZrOGhTVT0iLCJtYWMiOiI1OTFmNjc0MjhiNzk3ZWJlNGMyNmE1NTIyNzA2MGNlMGY0YmZmNWQ3MmIwYmRhN2ZhZDE0NWQwMmJjNGUzMjkyIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>
     
      <p class="text-center bb s2 mb-3">A Short Guide to Essay Planning</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_JtfbXSjR" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Planning-an-Essay-YouTube.html?player=onlinerec&at=eyJpdiI6ImRNaEM2TWlDVTArQjRjemtZUGQxbFE9PSIsInZhbHVlIjoiQ3o5UUhxS01RQzdYN2pUSzcvSkVNcmZFQWRrdnFXL2JIb3VGcW5qaFlFMD0iLCJtYWMiOiJiNzY2M2UyNzE5OTc5NzczYjFmOTVkNzBkNjEyMjI1N2RkYTBhMTljMzA1YWQ1M2I4NjAxZjdlYmZhZTkyYTczIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

  
  
      <p class="text-center bb s6 mt-8 mb-8">Phase 4 - Day 19 to 25</p>

  <p class="text-center bb s2 mb-3">CES Essay Masterclass</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_HWZRPDSi" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Basic-Concepts-of-IELTS-Essay-Writing.html?player=onlinerec&at=eyJpdiI6IjVJN0F2d1VzVEdkVTJZeDJLYlFsb1E9PSIsInZhbHVlIjoidDVlN2l2OUxNTHZ4Nzk2L0NJNzRDN3htNGc5emNoeFVhR0pSTGc1WTRiTT0iLCJtYWMiOiJmOThlMGFjNGMxYjg2Nzg3MjFkNDAwNWNlY2RiODA4Yzg1ZDM3ZTBjMzIyNWM0ZTUzMTliMmZhOWQyMTI4ZDc0IiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

<p class="text-center bb s2 mb-3">Map Masterclass</p>
<div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 63.81%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 63.81%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_4t0sL1jG" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Map-Class.html?player=onlinerec&at=eyJpdiI6IlBERzFXaEJtOFZHL0dYSDJxb1ZsSkE9PSIsInZhbHVlIjoiMEtBVGVnWmpmbmxNd3ZkL1Q3amF2VDJMZ0hBdTVXcGpQKzV2QkpWNUZBQT0iLCJtYWMiOiI5OTRmODc5ZmE5MTY2Yjc3NDg0YzI3YzVmNDIwYWNlYTQzNDExNTgyNDI1NTk3YjViM2U1MmVhYzYxYTUyMWJiIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>


      <p class="text-center bb s2 mb-3">5 Big IELTS Speaking Part 3 Tips</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_gko1w9Vh" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/5-BIG-IELTS-Speaking-Part-3-TIPS.html?player=onlinerec&at=eyJpdiI6IjRYT0lBNXhOKyt2OGhmUml5Z01IbFE9PSIsInZhbHVlIjoiTytuckJLajFXMUZsR1gwbWR0aEc0RnFmeUVDOWVHOEI0KzBwV25CNzVhdz0iLCJtYWMiOiIxYWJkZTg3OWI1YjQ1ZjQ2YTMwOGJkOTAyMzM4MGRmYThlODljYWIxMzliZmEwZmQ0OGRlMjc1M2E4YWRhNTAzIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>


      <p class="text-center bb s2 mb-3">Listening MCQ Tips and Tricks</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_QXnkuxpV" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/-Listening-MCQs-Improvement-Guide.html?player=onlinerec&at=eyJpdiI6IlIrTmtsN2gxZlJ0TnFLQTRENG42WWc9PSIsInZhbHVlIjoiengxbzI5Sko2ZDM2NHJ6ellWbnhsUUdTd1BnaGVpenRQYi85bEdGNXJjcz0iLCJtYWMiOiI5NmU5ODIxM2QwZmUwZDU3MzU4OGFjM2E5ZGVjMDVlMTIzM2JmYWRhMmVmNGQ0NGJlODIwNTYwMzNmN2I5ZmMyIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>


      <p class="text-center bb s2 mb-3">How to write good examples.</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_Va1wMic6" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/-Band-9-Examples-Masterclass-IELTS-Task-2.html?player=onlinerec&at=eyJpdiI6IjlPeHY0VWRFT1R4RDNhZi9sT1pzU1E9PSIsInZhbHVlIjoiK0lpem9wTEcyZUFJdE9Ncm5lNVpBd3Q1RmZVblBuc3N4UHBuNEFXdm51Zz0iLCJtYWMiOiJiMDVkMGQyMjk0YzBjNTAwZWM5OWE2YTk4NmQyMTk4YWZkZmM1NzkyNGYyOWY0ZTVhMWQxMTYyNDA4ZmIwOTc3IiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mb-3">Reading Lesson 8.1 - NMT (Name Matching Questions)</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_V5SpA1kN" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Lesson-8-Matching-Type-Questions.html?player=onlinerec&at=eyJpdiI6Iko4K3hpTGF4YUxJSlRENFlONGxCZWc9PSIsInZhbHVlIjoiT1pLNHpUbWVEazhCQXQwdjJxaW10UWNVeExzaW9CbE05eTU1OGlkZzFnQT0iLCJtYWMiOiIxODM0YzFmOWFjYzlhNjg1NDk5OTNlZTBmMjYwMmI5OGVkOTdlOGJhMjVjNDk2YmE1ZDY3MzBiMjMzYmJkZTRkIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>


      <p class="text-center bb s2 mb-3">Reading Lesson 8.2 - NMT Live demonstration</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_5nuBkmA1" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Lesson-8-1-Live-demonstration-NMT.html?player=onlinerec&at=eyJpdiI6IkdmdWF2Qi9rVEhIbklqWVRGNTdXeFE9PSIsInZhbHVlIjoiZzdVSXJ5c1BhVFJMWkhESE1CM3VyMyt2bXp2eEppdXpQelhtL3FwN0tCND0iLCJtYWMiOiJkYjNlN2M5YjM1ZTM3YjE2YzI3NWQxMDBhOTRmNzBiOTliOGE1MGEyYTlkNGU4MWQ5NjAwMzZiNzExOWMwOGM5IiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>


      <p class="text-center bb s2 mb-3">Reading Lesson 9.1 - Heading Type Questions</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_Ma7w4pMl" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Lesson-9-Headings-Type-Questions.html?player=onlinerec&at=eyJpdiI6Im9mYmlqcWFRekpyMXBvZDAyQS9mREE9PSIsInZhbHVlIjoiN2NmR295QVNxQld1cTBFNUZzT1FPWHRjbjVCamlDckJwRXR6ZzNBQjNQTT0iLCJtYWMiOiI5NzBiZmNhOWE3YTYxYzJhNGQwZjZiYjY1NzY3MDg5NjAyZDgwMzRiZGIyNTQ1ZjY2YTZlMTY4NDc0ZTcyYmYyIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mb-3">Reading Lesson 9.2 - Heading Live Demonstration</p>
      <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_HnJjHtBm" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Lesson-9-1-Live-demonstration-Headings.html?player=onlinerec&at=eyJpdiI6IlhNZVllY1A0UlFGbUEwNTVKZnR6Unc9PSIsInZhbHVlIjoicXNySzVNaEgzWEFYbUJFdmVzMUZCck12QmhDTFRmQlgrQ3F1L3RXQ2NxUT0iLCJtYWMiOiI2ZjY4NzBkZDUyMjVlODFiMTI2NTZlNjdmOWJmN2M1NjJlMGNiMzViYWUyNDNkNzc5YTdkNTZmN2ZlMWNiNjE1IiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>


  <p class="text-center bb s6 mt-8 mb-8">Phase 5 - Day 26 to 32</p>
  
  <p class="text-center bb s2 mb-3">Process Essay Masterclass</p>
  <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 70.59%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 70.59%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_gmesLvpk" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Process-Class-Full.html?player=onlinerec&at=eyJpdiI6Inp0blB5eVhOR083UUFqSWZFWHI0L0E9PSIsInZhbHVlIjoiQ0pZRE4xZFdyc2JCRkdlL0licjBwS1FTZzRWRngvRVpPd2JJdHBlY3N1VT0iLCJtYWMiOiJkMjJkMzIyZjg0MzA0OTQ3YmU3YTA5NmVmY2M2NTY1YWQ5OThiMzY0ZWMwYTQ5MDg3Y2EwZjZkNjM0NzYyNDU4IiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>

      <p class="text-center bb s2 mb-3">A short Guide to Idea Development</p>
     <div><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><figure style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%; margin-block-end: 0; margin-block-start: 0; margin-inline-start: 0; margin-inline-end: 0;" ><iframe id="pv_pG609RJa" src="https://media.publit.io/file/NewRecordngs/OfflineVideos/Developing-Ideas.html?player=onlinerec&at=eyJpdiI6IlVuN0s5SmNqRXlIZUhNeERLU25OMlE9PSIsInZhbHVlIjoibGlJZ2ViZCtnTjFUdmg4UWVQWDlERlM4STQyU0pVTGZxNURXNGJqNHNRaz0iLCJtYWMiOiI3Zjg1MDQzOGMxYzliZWIzYmQzOTQ5YWQ0ZDQzNzJhZjZlMTBiZTk2ZDI1YmM3NGVkNDZhMmQ2YjRjMjczMDdmIiwidGFnIjoiIn0=" scrolling="no" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow:hidden;" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" ></iframe></figure></div></div>



  
  </section>
  
  </section>